CREATE TABLE `assessment_records` (
	`id` text PRIMARY KEY NOT NULL,
	`assessment_version` text NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`name` text,
	`work_email` text,
	`company` text,
	`phone` text,
	`report_consent` integer DEFAULT false NOT NULL,
	`marketing_consent` integer DEFAULT false NOT NULL,
	`overall_score` integer,
	`owner_independence_score` integer,
	`operating_system_score` integer,
	`information_visibility_score` integer,
	`score_coverage` real NOT NULL,
	`score_confidence` text NOT NULL,
	`impact_confidence` text NOT NULL,
	`estimate_type` text NOT NULL,
	`recoverable_hours_low` real,
	`recoverable_hours_high` real,
	`annual_value_low` real,
	`annual_value_high` real,
	`risk_codes_json` text NOT NULL,
	`priority_ids_json` text NOT NULL,
	`lead_route` text NOT NULL,
	`narrative_source` text NOT NULL,
	`report_delivery_status` text NOT NULL
);
