import type { QuestionDefinition } from "./types";

export const ASSESSMENT_VERSION = "1.0.0";
export const COMPONENT_WEIGHTS = {
  ownerIndependence: 0.35,
  operatingSystem: 0.35,
  informationVisibility: 0.30,
} as const;

const anchors = (labels: [string, string, string, string, string]) => [
  { value: 0 as const, label: labels[0] },
  { value: 25 as const, label: labels[1] },
  { value: 50 as const, label: labels[2] },
  { value: 75 as const, label: labels[3] },
  { value: 100 as const, label: labels[4] },
  { value: "unknown" as const, label: "I do not know or cannot verify this" },
];

export const QUESTION_BANK: QuestionDefinition[] = [
  { id: "criticalDecisions", component: "ownerIndependence", weight: .30, required: true, prompt: "How often do material operating decisions wait for owner approval?", options: anchors(["Nearly every decision waits for the owner", "Most decisions wait, with limited exceptions", "It varies by manager or situation", "Most decisions are delegated within understood limits", "Defined decisions are made at the appropriate level"]) },
  { id: "twoWeekAbsence", component: "ownerIndependence", weight: .25, required: true, prompt: "What would happen if the owner were unavailable for two weeks?", options: anchors(["Routine work and decisions would stall", "Significant work would wait or require contact", "Core work continues but issues accumulate", "Operations continue with a few defined exceptions", "Operations and management cadence continue without contact"]) },
  { id: "managerAuthority", component: "ownerIndependence", weight: .20, required: true, prompt: "How clearly can managers make decisions without owner approval?", options: anchors(["Managers execute tasks but lack decision authority", "Authority is narrow and regularly overridden", "Authority varies by function or situation", "Managers usually decide within understood limits", "Decision rights, limits, and escalation paths are explicit"]) },
  { id: "exceptionResolution", component: "ownerIndependence", weight: .15, required: true, prompt: "How are recurring operating exceptions resolved?", options: anchors(["Exceptions routinely escalate to the owner", "Most exceptions escalate despite manager involvement", "Common issues are resolved but treatment varies", "Teams resolve most standard exceptions", "Standard exceptions follow defined rules at the correct level"]) },
  { id: "workWaiting", component: "ownerIndependence", weight: .10, required: true, prompt: "How often does routine work wait for owner input?", options: anchors(["Work queues form regularly", "Waiting occurs most weeks", "Waiting occurs in specific areas", "Waiting is uncommon and limited", "Owner input rarely blocks routine execution"]) },
  { id: "relationshipConcentration", component: "ownerIndependence", weight: .10, required: false, appliesWhen: (c) => c.relationshipLedByOwner, prompt: "How dependent are key external relationships on the owner?", options: anchors(["Key relationships depend almost entirely on the owner", "The owner remains the essential relationship holder", "Relationships are shared but the owner is central", "Coverage exists with limited owner dependence", "Relationships are institutionally owned and documented"]) },

  { id: "workflowDocumentation", component: "operatingSystem", weight: .25, required: true, prompt: "How consistently are critical recurring workflows documented and used?", options: anchors(["Critical workflows reside in individual memory", "Documentation is isolated or rarely used", "Selected workflows are documented but incomplete", "Most critical workflows are current and used", "Critical workflows are current, accessible, and routinely used"]) },
  { id: "processOwnership", component: "operatingSystem", weight: .20, required: true, prompt: "How clearly are critical outcomes and workflows owned?", options: anchors(["Ownership is assumed or disputed", "Ownership is person-dependent and often unclear", "Ownership is clear within selected functions", "Most workflows have accountable owners", "Critical outcomes and workflows have explicit accountable owners"]) },
  { id: "decisionRules", component: "operatingSystem", weight: .20, required: true, prompt: "How explicit are decision thresholds and escalation rules?", options: anchors(["Teams rely on owner intervention", "Rules are informal and manager-specific", "Common rules exist but vary", "Most thresholds are understood and followed", "Decision thresholds and escalation paths are explicit"]) },
  { id: "crossTraining", component: "operatingSystem", weight: .15, required: true, prompt: "How resilient is coverage for critical responsibilities?", options: anchors(["Critical work has single points of failure", "Backup coverage is informal or untested", "Selected roles have workable backup coverage", "Most critical responsibilities have trained backups", "Critical responsibilities have tested backup coverage"]) },
  { id: "managementCadence", component: "operatingSystem", weight: .20, required: true, prompt: "How reliably does the management cadence produce decisions and accountability?", options: anchors(["Reviews are reactive or irregular", "Meetings occur without consistent decisions", "Recurring reviews exist but follow-through varies", "Reviews usually connect measures, decisions, and owners", "A defined cadence consistently drives decisions and accountability"]) },
  { id: "crossTeamConsistency", component: "operatingSystem", weight: .15, required: false, appliesWhen: (c) => c.organizationShape === "multipleTeams", prompt: "How consistently do teams execute shared critical workflows?", options: anchors(["Teams use materially different approaches", "Differences regularly create handoff problems", "Common intent exists but execution varies", "Shared standards govern most handoffs", "Shared standards consistently govern critical workflows"]) },

  { id: "kpiAvailability", component: "informationVisibility", weight: .25, required: true, prompt: "Are current KPIs available when leaders need to make decisions?", options: anchors(["Leaders cannot access current measures", "Measures require significant ad hoc preparation", "Core KPIs exist but are delayed or incomplete", "Most decision-relevant KPIs are timely", "Current decision-relevant KPIs are available within cadence"]) },
  { id: "manualReporting", component: "informationVisibility", weight: .20, required: true, prompt: "How much recurring management reporting is assembled manually?", options: anchors(["Nearly all recurring reporting is manual", "Most reporting requires manual assembly", "Automation exists but material manual work remains", "Routine reporting is mostly automated with review", "Routine reporting is automated with controlled human review"]) },
  { id: "dataTrust", component: "informationVisibility", weight: .20, required: true, prompt: "How much time do leaders spend reconciling competing numbers?", options: anchors(["Leaders regularly debate whose numbers are correct", "Reconciliation is required for most reviews", "Selected measures are trusted after reconciliation", "Most measures use common definitions and sources", "Controlled definitions and sources produce trusted information"]) },
  { id: "detectionSpeed", component: "informationVisibility", weight: .20, required: true, prompt: "How early are operating problems detected?", options: anchors(["Problems surface through customer or cash impact", "Problems are usually detected after material impact", "Reviews identify problems after a meaningful delay", "Most issues surface early enough for corrective action", "Leading and lagging indicators reveal issues early enough to act"]) },
  { id: "kpiCadence", component: "informationVisibility", weight: .15, required: true, prompt: "What happens after KPIs are reviewed?", options: anchors(["Metrics are irregular and have no clear owner", "Reviews occur without consistent actions", "Actions are assigned but follow-through varies", "Reviews usually produce owned and tracked actions", "Reviews consistently produce decisions, owners, and tracked actions"]) },
  { id: "systemConnectivity", component: "informationVisibility", weight: .10, required: false, appliesWhen: (c) => c.coreSystemCount === "twoOrMore", prompt: "How reliably does critical information move between systems?", options: anchors(["Critical information is repeatedly re-keyed", "Manual transfers dominate and cause recurring errors", "Selected integrations exist with significant gaps", "Most critical flows are controlled with limited gaps", "Critical systems exchange required information through controlled workflows"]) },
];
